name: followers

on:
  schedule:
    - cron: "0 * * * *" # Once an hour.

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run:  'echo "" > temp.txt'
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.5
        
    - name: Bundle install
      run: bundle install --jobs 4 --retry 3
      
    - name: create-readme
      run: bundle exec ruby create-readme.rb
      
    - name: commit and push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_user_name: GitHub Actions
        commit_user_email: actions@github.com
        commit_author: GitHub Actions <actions@github.com>
        commit_message: Update README.md
        file_pattern: README.md
